version: "3"
services:
  smtp2signal:
    hostname: "smtp2signal.docker"
    build: ./smtp2signal
    restart: always
    environment:
      SIGNAL_CLI_BASE_URL: http://signal-cli-rest-api:8080/
      SIGNAL_SMTP_TOKEN_FILE: /home/smtp2signal.token 
    ports:
      - 8025:8025
    volumes:
      - "./data/smtp2signal:/home"
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.94
    restart: always
    environment:
      - MODE=json-rpc
    volumes:
      - "./data/signal-cli:/home/.local/share/signal-cli" 
